version: '3.8'
services:
  #your-app-service:
   # image: your-app-image
    #ports:
     # - "3000:3000"
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
  k6:
    image: grafana/k6
    volumes:
      - type: bind
        source: ./load-testing
        target: /load-testing
    entrypoint: ["k6", "run", "/load-testing/load-test.js"]
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
