global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
#- job_name: 'express-app'
 # static_configs:
  #  - targets: ['host.docker.internal:3000'] # No "http://"
  - job_name: 'k6-load-tests'
    static_configs:
      - targets: ['k6:9000']


