global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
- job_name: 'express-app'
  static_configs:
    - targets: ['host.docker.internal:3000'] # No "http://"